/**
 * ------------------------ Auto-generated Code ------------------------
 *           This code was generated by the Insieme Compiler
 * ---------------------------------------------------------------------
 */
#include <algorithm>
#include <alloca.h>
#include <allscale/runtime.hpp>
#include <chrono>
#include <cstdlib>
#include <iostream>
#include <stdbool.h>
#include <stdint.h>
#include <utility>

#ifdef __cplusplus
#define INS_INIT(...) __VA_ARGS__
#else
#define INS_INIT(...) (__VA_ARGS__)
#endif
#ifdef __cplusplus
#include <new>
#define INS_INPLACE_INIT(Loc,Type) new(Loc) Type
#else
#define INS_INPLACE_INIT(Loc,Type) *(Loc) = (Type)
#endif
#ifdef __cplusplus
				/** Workaround for libstdc++/libc bug.
				 *  There's an inconsistency between libstdc++ and libc regarding whether
				 *  ::gets is declared or not, which is only evident when using certain
				 *  compilers and language settings
				 *  (tested positively with clang 3.9 --std=c++14 and libc 2.17).
				 */
				#include <initializer_list>  // force libstdc++ to include its config
				#undef _GLIBCXX_HAVE_GETS    // correct broken config
#endif

/* ------- Program Code --------- */

struct __wi_main_name {
    static const char* name() { return "__wi_main"; }
};

struct __wi_main_variant_0;
typedef struct __wi_main_variant_0 __wi_main_variant_0;

struct __wi_main_variant_1;
typedef struct __wi_main_variant_1 __wi_main_variant_1;

struct __wi_main_can_split;
typedef struct __wi_main_can_split __wi_main_can_split;

using __wi_main_work = allscale::work_item_description<int32_t, __wi_main_name, allscale::no_serialization, __wi_main_variant_0, __wi_main_variant_1, __wi_main_can_split >;

/* ------- Function Definitions --------- */
int32_t main(int32_t var_0, char** var_1) {
    return allscale::runtime::main_wrapper<__wi_main_work >(var_0, var_1);
}

struct IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41;
typedef struct IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41;

struct IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 {
    int32_t const& capture_0;
    int32_t**& capture_1;
    int32_t**& capture_2;
    int32_t**& capture_3;;
    IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41(IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 const& p2) = default;
    IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41(IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41&& p2) = default;
    IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41(int32_t const& p2, int32_t**& p3, int32_t**& p4, int32_t**& p5);
    ~IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41() = default;
    IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41& operator=(IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 const& p2) = default;
    IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41& operator=(IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41&& p2) = default;
    void operator()(int32_t p2) const;
};

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int;
typedef struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int;

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int;
typedef struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int;

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int;
typedef struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int;

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int {
    int32_t _begin;
    int32_t _end;;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int();
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& p2) = default;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int&& p2) = default;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int(int32_t const& p2, int32_t const& p3);
    ~IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int() = default;
    bool IMP_empty_returns_bool() const;
    uint64_t IMP_size_returns_size_t() const;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int& operator=(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& p2) = default;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int& operator=(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int&& p2) = default;
    int32_t const& begin_returns_constint() const;
    bool covers_returns_bool(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& p2) const;
    int32_t const& end_returns_constint() const;
    void forEach_lambdahomeuserdevruntime_analysissrcmatrixmatrixcpp_52_41_returns_void(IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 const& p2) const;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int grow_returns_allscaleapiuserdetailrangeint(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& p2, int32_t p3) const;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int shrink_returns_allscaleapiuserdetailrangeint(int32_t p2) const;
    std::pair<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int > split_returns_stdpairrangeintrangeint() const;
};

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int {
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int _range;
    allscale::treeture<void > handle;;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int();
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& p2);
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int const& p2) = default;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int&& p2) = default;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& p2, allscale::treeture<void > const& p3);
    ~IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int() = default;
    operator allscale::treeture<void >() const;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int& operator=(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int const& p2) = default;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int& operator=(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int&& p2) = default;
    allscale::treeture<void > const& getHandle_returns_constcoretask_reference() const;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int getLeft_returns_iteration_referenceint() const;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& getRange_returns_constrangeint() const;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int getRight_returns_iteration_referenceint() const;
    void wait_returns_void() const;
};

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int : public IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int {
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int();
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int&& p2) = default;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& p2, allscale::treeture<void >&& p3);
    ~IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int();
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int& operator=(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int&& p2) = default;
};

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_SubDependencies_struct_space_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies;
typedef struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_SubDependencies_struct_space_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_SubDependencies_struct_space_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies;

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies;
typedef struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies;

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_dependency;
typedef struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_dependency IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_dependency;

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_dependency {
};

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies : public IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_dependency {
    ;
    ;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_SubDependencies_struct_space_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies split() const;
};

struct __wi_allscale_wi_1_variant_1;
typedef struct __wi_allscale_wi_1_variant_1 __wi_allscale_wi_1_variant_1;

struct __wi_allscale_wi_1_variant_0;
typedef struct __wi_allscale_wi_1_variant_0 __wi_allscale_wi_1_variant_0;

struct __wi_allscale_wi_1_can_split;
typedef struct __wi_allscale_wi_1_can_split __wi_allscale_wi_1_can_split;

struct __wi_allscale_wi_1_name {
    static const char* name() { return "__wi_allscale_wi_1"; }
};

using __wi_allscale_wi_1_work = allscale::work_item_description<void, __wi_allscale_wi_1_name, allscale::no_serialization, __wi_allscale_wi_1_variant_0, __wi_allscale_wi_1_variant_1, __wi_allscale_wi_1_can_split >;

/* ------- Function Definitions --------- */
allscale::treeture<void > allscale_fun_186(allscale::runtime::dependencies const& var_0, hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_1) {
    return allscale::spawn_with_dependencies<__wi_allscale_wi_1_work >(var_0, hpx::util::get<0 >(var_1), hpx::util::get<1 >(var_1), hpx::util::get<2 >(var_1));
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int allscale_fun_183(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& var_0, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 const& var_1, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies const& var_2) {
    return {var_0, allscale::runtime::make_prec_operation<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, void >(INS_INIT(hpx::util::tuple<IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 >){var_1, var_1}, &allscale_fun_186)(var_0)};
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_pfor_int_lambda_slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_struct_space_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies_returns_detail_colon__colon_loop_reference_lt_int_gt_(int32_t const& var_0, int32_t const& var_1, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 const& var_2, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies const& var_3) {
    return (IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int&&)allscale_fun_183(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int(var_0, var_1), var_2, var_3);
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_pfor_int_lambda_slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_returns_detail_colon__colon_loop_reference_lt_int_gt_(int32_t const& var_0, int32_t const& var_1, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 const& var_2) {
    return (IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int&&)IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_pfor_int_lambda_slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_struct_space_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies_returns_detail_colon__colon_loop_reference_lt_int_gt_(var_0, var_1, var_2, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies());
}
/* ------- Function Definitions --------- */
void IMP_execute(int32_t** var_0, int32_t** var_1, int32_t** var_2, int32_t var_3) {
    std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<int64_t, std::ratio<1, 1000000000 > > > var_4 = (std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<int64_t, std::ratio<1, 1000000000 > > >&&)std::chrono::system_clock::now();
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_pfor_int_lambda_slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_returns_detail_colon__colon_loop_reference_lt_int_gt_(0, var_3, INS_INIT(IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41){var_3, var_2, var_0, var_1});
    std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<int64_t, std::ratio<1, 1000000000 > > > var_5 = (std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<int64_t, std::ratio<1, 1000000000 > > >&&)std::chrono::system_clock::now();
    std::chrono::duration<int64_t, std::ratio<1, 1000000000 > > var_6 = (std::chrono::duration<int64_t, std::ratio<1, 1000000000 > > const&)(var_5 - var_4);
    std::cout << var_6.count() << &std::endl;
}
struct allscale_type_12;
typedef struct allscale_type_12 allscale_type_12;

struct allscale_type_12 {
    char data[8];;
};

/* ------- Function Definitions --------- */
int32_t* allscale_fun_26(uint64_t var_0) {
    uint64_t var_1 = var_0;
    return new int32_t[var_1];
}
/* ------- Function Definitions --------- */
int32_t** new_arr_fun(uint64_t var_0) {
    uint64_t var_1 = var_0;
    return new int32_t*[var_1];
}
/* ------- Function Definitions --------- */
int32_t** IMP_create_array_2d(int32_t var_0) {
    int32_t** var_1 = new_arr_fun((uint64_t)((uint64_t)var_0));
    {
        for (int32_t var_2 = 0; var_2 < var_0; ++var_2) {
            var_1[var_2] = allscale_fun_26((uint64_t)((uint64_t)var_0));
        };
    };
    return var_1;
}
/* ------- Function Definitions --------- */
int32_t** IMP_init(int32_t var_0) {
    int32_t** var_1 = IMP_create_array_2d(var_0);
    {
        for (int32_t var_2 = 0; var_2 < var_0; ++var_2) {
            {
                for (int32_t var_3 = 0; var_3 < var_0; ++var_3) {
                    var_1[var_2][var_3] = var_2 == var_3 ? 1 : 0;
                };
            };
        };
    };
    return var_1;
}
struct allscale_type_17;
typedef struct allscale_type_17 allscale_type_17;

struct allscale_type_17 {
    char data[29];;
};

struct allscale_type_13;
typedef struct allscale_type_13 allscale_type_13;

struct allscale_type_13 {
    char data[15];;
};

struct allscale_type_19;
typedef struct allscale_type_19 allscale_type_19;

struct allscale_type_19 {
    char data[27];;
};

struct allscale_type_207;
typedef struct allscale_type_207 allscale_type_207;

struct allscale_type_207 {
    char data[11];;
};

/* ------- Function Definitions --------- */
void IMP_check(int32_t** var_0, int32_t var_1) {
    int32_t var_2 = 0;
    while (var_2 < var_1) {
        {
            int32_t var_3 = 0;
            while (var_3 < var_1) {
                {
                    if (var_2 == var_3 && var_0[var_2][var_3] != 1) {
                        std::cerr << "mult error" << &std::endl;
                    };
                    if (var_2 != var_3 && var_0[var_2][var_3] != 0) {
                        std::cerr << "mult error" << &std::endl;
                    };
                };
                var_3++;
            };
        };
        var_2++;
    };
}
/* ------- Function Definitions --------- */
void IMP_delete_array(int32_t** var_0, int32_t var_1) {
    {
        for (int32_t var_2 = 0; var_2 < var_1; ++var_2) {
            delete[] var_0[var_2];
        };
    };
    delete[] var_0;
}
/* ------- Function Definitions --------- */
int32_t IMP_main(int32_t var_0, char** var_1) {
    int32_t var_2 = -1;
    {
        int32_t var_3 = 0;
        while (var_3 < var_0) {
            if ((int32_t)var_1[var_3][0] == (int32_t)((char)'-')) {
                {
                    for (int32_t var_4 = var_3 + 1; var_4 < var_0; ++var_4) {
                        var_1[var_4 - 1] = var_1[var_4];
                    };
                };
                var_0--;
            };
            var_3++;
        };
    };
    if (var_0 != 2) {
        std::cerr << "Usage: " << var_1[0] << " [MATRIX SIZE]" << &std::endl;
        var_2 = 700;
        std::cerr << "Setting default matrix size " << var_2 << &std::endl;
    } else {
        var_2 = atoi(var_1[1]);
        if (var_2 < 0) {
            std::cerr << "Matrix size has to be >= 0" << &std::endl;
            return 1;
        };
    };
    int32_t** var_5 = IMP_init(var_2);
    int32_t** var_6 = IMP_init(var_2);
    int32_t** var_7 = IMP_create_array_2d(var_2);
    IMP_execute(var_5, var_6, var_7, var_2);
    IMP_check(var_7, var_2);
    IMP_delete_array(var_5, var_2);
    IMP_delete_array(var_6, var_2);
    IMP_delete_array(var_7, var_2);
    return 0;
}
ALLSCALE_REGISTER_TREETURE_TYPE(int32_t)
/* ------- Function Definitions --------- */
allscale::treeture<int32_t > allscale_fun_3(hpx::util::tuple<int32_t, char** > const& var_0) {
    return allscale::treeture<int32_t >(IMP_main(hpx::util::get<0 >(var_0), hpx::util::get<1 >(var_0)));
}
struct __wi_main_variant_0 {
    static allscale::treeture<int32_t > execute(hpx::util::tuple<int32_t, char** > const& var_0);
    static constexpr bool valid = true;
};

/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41::IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41(int32_t const& var_1, int32_t**& var_2, int32_t**& var_3, int32_t**& var_4) : capture_0(var_1), capture_1(var_2), capture_2(var_3), capture_3(var_4) { }
/* ------- Function Definitions --------- */
void IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41::operator()(int32_t var_1) const {
    for (int32_t var_2 = 0; var_2 < (*this).capture_0; ++var_2) {
        {
            (*this).capture_1[var_1][var_2] = 0;
            {
                for (int32_t var_3 = 0; var_3 < (*this).capture_0; ++var_3) {
                    (*this).capture_1[var_1][var_2] += (*this).capture_2[var_1][var_3] * (*this).capture_3[var_3][var_2];
                };
            };
        };
    };
}
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
bool IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::IMP_empty_returns_bool() const {
    return (*this).IMP_size_returns_size_t() == (uint64_t)0;
}
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
int32_t IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_access_int_returns_typename_space_std_colon__colon_enable_if_lt_std_colon__colon_is_integral_lt_int_gt__colon__colon_value_comma__space_int_gt__colon__colon_type(int32_t var_0) {
    return var_0;
}
/* ------- Function Definitions --------- */
void IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_forEach_int_lambda_slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_returns_void(int32_t const& var_0, int32_t const& var_1, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 const& var_2) {
    for (int32_t var_3 = var_0; var_3 < var_1; ++var_3) {
        var_2.operator()(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_access_int_returns_typename_space_std_colon__colon_enable_if_lt_std_colon__colon_is_integral_lt_int_gt__colon__colon_value_comma__space_int_gt__colon__colon_type(var_3));
    };
}
/* ------- Function Definitions --------- */
void IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::forEach_lambdahomeuserdevruntime_analysissrcmatrixmatrixcpp_52_41_returns_void(IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 const& var_1) const {
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_forEach_int_lambda_slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_returns_void((*this)._begin, (*this)._end, var_1);
}
/* ------- Function Definitions --------- */
std::pair<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int > IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_spliter_lt_int_gt__colon__colon_split_returns_std_colon__colon_pair_lt_rng_comma__space_rng_gt_(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& var_0) {
    int32_t const& var_1 = var_0.begin_returns_constint();
    int32_t const& var_2 = var_0.end_returns_constint();
    int32_t var_3 = var_1 + (var_2 - var_1) / 2;
    return (std::pair<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int >&&)std::make_pair(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int(var_1, var_3), IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int(var_3, var_2));
}
/* ------- Function Definitions --------- */
std::pair<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int > IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::split_returns_stdpairrangeintrangeint() const {
    return (std::pair<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int >&&)IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_spliter_lt_int_gt__colon__colon_split_returns_std_colon__colon_pair_lt_rng_comma__space_rng_gt_(*this);
}
/* ------- Function Definitions --------- */
int32_t IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_shrink_int_returns_int(int32_t const& var_0, int32_t const& var_1, int32_t var_2) {
    return std::max(var_1, var_0 - var_2);
}
/* ------- Function Definitions --------- */
int32_t IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_grow_int_returns_int(int32_t const& var_0, int32_t const& var_1, int32_t var_2) {
    return std::min(var_1, var_0 + var_2);
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::grow_returns_allscaleapiuserdetailrangeint(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& var_1, int32_t var_2) const {
    return (IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int&&)IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_shrink_int_returns_int((*this)._begin, var_1.begin_returns_constint(), var_2), IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_grow_int_returns_int((*this)._end, var_1.end_returns_constint(), var_2));
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int() : _begin(0), _end(0) { }
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int(int32_t const& var_1, int32_t const& var_2) : _begin(var_1), _end(var_2) {
    if ((*this).IMP_empty_returns_bool()) {
        (*this)._end = (*this)._begin;
    };
}
struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_volume_int;
typedef struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_volume_int IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_volume_int;

struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_volume_int {
    ;
    ;
    uint64_t operator()(int32_t p2, int32_t p3) const;
};

/* ------- Function Definitions --------- */
uint64_t IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::IMP_size_returns_size_t() const {
    return IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_volume_int().operator()((*this)._begin, (*this)._end);
}
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
uint64_t IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_volume_int::operator()(int32_t var_1, int32_t var_2) const {
    return (uint64_t)(var_1 < var_2 ? var_2 - var_1 : 0);
}
/* ------- Function Definitions --------- */
int32_t const& IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::begin_returns_constint() const {
    return (*this)._begin;
}
/* ------- Function Definitions --------- */
bool IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_covers_int_returns_bool(int32_t const& var_0, int32_t const& var_1, int32_t const& var_2, int32_t const& var_3) {
    return var_2 >= var_3 || var_0 <= var_2 && var_3 <= var_1;
}
/* ------- Function Definitions --------- */
bool IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::covers_returns_bool(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& var_1) const {
    return IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_covers_int_returns_bool((*this)._begin, (*this)._end, var_1._begin, var_1._end);
}
/* ------- Function Definitions --------- */
int32_t const& IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::end_returns_constint() const {
    return (*this)._end;
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int::shrink_returns_allscaleapiuserdetailrangeint(int32_t var_1) const {
    return (IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int&&)(*this).grow_returns_allscaleapiuserdetailrangeint(*this, 0 - var_1);
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int::IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int() : IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int()) { }
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int::IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& var_1) : _range(var_1), handle(allscale::make_ready_treeture()) { }
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int::IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& var_1, allscale::treeture<void > const& var_2) : _range(var_1), handle(var_2) { }
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int::operator allscale::treeture<void >() const {
    return (*this).handle;
}
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
allscale::treeture<void > const& IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int::getHandle_returns_constcoretask_reference() const {
    return (*this).handle;
}
/* ------- Function Definitions --------- */
std::pair<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int > allscale_fun_142(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& var_0) {
    int32_t const& var_1 = var_0.begin_returns_constint();
    int32_t const& var_2 = var_0.end_returns_constint();
    int32_t var_3 = var_1 + (var_2 - var_1) / 2;
    return (std::pair<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int >&&)std::make_pair(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int(var_1, var_3), IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int(var_3, var_2));
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int::getLeft_returns_iteration_referenceint() const {
    return {allscale_fun_142((*this)._range).first, (*this).handle.get_left_child()};
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int::getRight_returns_iteration_referenceint() const {
    return {allscale_fun_142((*this)._range).second, (*this).handle.get_right_child()};
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int::getRange_returns_constrangeint() const {
    return (*this)._range;
}
/* ------- Function Definitions --------- */
void IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int::wait_returns_void() const {
    if ((*this).handle.valid()) {
        (*this).handle.wait();
    };
}
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int::IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int() : IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int()) { }
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int::IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const& var_1, allscale::treeture<void >&& var_2) : IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int(var_1, std::move(var_2)) { }
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int::~IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_loop_reference_int() {
    (*(IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_iteration_reference_int*)this).wait_returns_void();
}
struct IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_SubDependencies_struct_space_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies {
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies left;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies right;;
};

/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_SubDependencies_struct_space_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies::split() const {
    return (IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_SubDependencies_struct_space_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies&&)IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_SubDependencies_struct_space_allscale_colon__colon_api_colon__colon_user_colon__colon_no_dependencies();
}
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
void allscale_fun_197(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    hpx::util::get<0 >(var_0).forEach_lambdahomeuserdevruntime_analysissrcmatrixmatrixcpp_52_41_returns_void(*(const IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41*)(&hpx::util::get<2 >(var_0)));
    return (void)0;
}
/* ------- Function Definitions --------- */
void allscale_fun_195(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    hpx::util::get<0 >(var_0).forEach_lambdahomeuserdevruntime_analysissrcmatrixmatrixcpp_52_41_returns_void(*(const IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41*)(&hpx::util::get<1 >(var_0)));
}
/* ------- Function Definitions --------- */
bool allscale_fun_193(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    return hpx::util::get<0 >(var_0).IMP_size_returns_size_t() <= (uint64_t)1;
}
/* ------- Function Definitions --------- */
void rec(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    if (allscale_fun_193(var_0)) {
        return allscale_fun_195(var_0);
    } else {
        return allscale_fun_197(var_0);
    };
}
/* ------- Function Definitions --------- */
allscale::treeture<void > allscale_fun_191(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    return rec(var_0), allscale::make_ready_treeture();
}
struct __wi_allscale_wi_1_variant_1 {
    static allscale::treeture<void > execute(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0);
    static constexpr bool valid = true;
};

allscale::treeture<void > __wi_allscale_wi_1_variant_1::execute(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    return allscale_fun_191(var_0);
}
/* ------- Function Definitions --------- */
allscale::treeture<void > allscale_fun_190(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    std::pair<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int > var_1 = (std::pair<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int >&&)hpx::util::get<0 >(var_0).split_returns_stdpairrangeintrangeint();
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int& var_2 = var_1.first;
    IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int& var_3 = var_1.second;
    return allscale::runtime::treeture_parallel(allscale::runtime::after(), std::move(allscale::spawn_with_dependencies<__wi_allscale_wi_1_work >(allscale::runtime::after(), (IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const&)var_2, hpx::util::get<1 >(var_0), hpx::util::get<2 >(var_0))), std::move(allscale::spawn_with_dependencies<__wi_allscale_wi_1_work >(allscale::runtime::after(), (IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int const&)var_3, hpx::util::get<1 >(var_0), hpx::util::get<2 >(var_0))));
}
/* ------- Function Definitions --------- */
allscale::treeture<void > allscale_fun_188(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    return allscale_fun_190(var_0);
}
struct __wi_allscale_wi_1_variant_0 {
    static allscale::treeture<void > execute(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0);
    static constexpr bool valid = true;
};

allscale::treeture<void > __wi_allscale_wi_1_variant_0::execute(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    return allscale_fun_188(var_0);
}
/* ------- Function Definitions --------- */
bool allscale_fun_198(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    return !allscale_fun_193(var_0);
}
struct __wi_allscale_wi_1_can_split {
    static bool call(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0);
};

bool __wi_allscale_wi_1_can_split::call(hpx::util::tuple<IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_detail_colon__colon_range_int, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41, IMP___anon_tagtype__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41_const_space_int_space__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__int_space__star__star__ampersand__void_int_IMLOC__slash_home_slash_user_slash_dev_slash_runtime_analysis_slash_src_slash_matrix_slash_matrix_dot_cpp_52_41 > const& var_0) {
    return allscale_fun_198(var_0);
}
allscale::treeture<int32_t > __wi_main_variant_0::execute(hpx::util::tuple<int32_t, char** > const& var_0) {
    return allscale_fun_3(var_0);
}
struct __wi_main_variant_1 {
    static allscale::treeture<int32_t > execute(hpx::util::tuple<int32_t, char** > const& var_0);
    static constexpr bool valid = true;
};

allscale::treeture<int32_t > __wi_main_variant_1::execute(hpx::util::tuple<int32_t, char** > const& var_0) {
    return allscale_fun_3(var_0);
}
/* ------- Function Definitions --------- */
bool allscale_fun_208(hpx::util::tuple<int32_t, char** > const& var_0) {
    return (bool)false;
}
struct __wi_main_can_split {
    static bool call(hpx::util::tuple<int32_t, char** > const& var_0);
};

bool __wi_main_can_split::call(hpx::util::tuple<int32_t, char** > const& var_0) {
    return allscale_fun_208(var_0);
}

