/**
 * ------------------------ Auto-generated Code ------------------------ 
 *           This code was generated by the Insieme Compiler 
 * --------------------------------------------------------------------- 
 */
#include <alloca.h>
#include <allscale/runtime.hpp>
#include <allscale/utils/assert.h>
#include <assert.h>
#include <iostream>
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
#define INS_INIT(...) __VA_ARGS__
#else
#define INS_INIT(...) (__VA_ARGS__)
#endif
#ifdef __cplusplus
#include <new>
#define INS_INPLACE_INIT(Loc,Type) new(Loc) Type
#else
#define INS_INPLACE_INIT(Loc,Type) *(Loc) = (Type)
#endif
#ifdef __cplusplus
				/** Workaround for libstdc++/libc bug.
				 *  There's an inconsistency between libstdc++ and libc regarding whether
				 *  ::gets is declared or not, which is only evident when using certain
				 *  compilers and language settings
				 *  (tested positively with clang 3.9 --std=c++14 and libc 2.17).
				 */
				#include <initializer_list>  // force libstdc++ to include its config
				#undef _GLIBCXX_HAVE_GETS    // correct broken config
#endif

/* ------- Program Code --------- */

struct __wi_main_variant_0;
typedef struct __wi_main_variant_0 __wi_main_variant_0;

struct __wi_main_variant_1;
typedef struct __wi_main_variant_1 __wi_main_variant_1;

struct __wi_main_name {
    static const char* name() { return "__wi_main"; }
};

using __wi_main_work = allscale::work_item_description<int32_t, __wi_main_name, allscale::no_serialization, __wi_main_variant_0, __wi_main_variant_1 >;

/* ------- Function Definitions --------- */
int32_t main() {
    return allscale::runtime::main_wrapper<__wi_main_work >();
}

struct IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19;
typedef struct IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19;

typedef int32_t allscale_type_13();

typedef allscale_type_13* allscale_type_14;

struct IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 {
    operator allscale_type_14() const;
    ;
    ;
    int32_t operator()() const;
};

ALLSCALE_REGISTER_TREETURE_TYPE(int32_t)
struct IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3;
typedef struct IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3 IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3;

struct IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3 {
    ;
    ;
};

struct __wi_allscale_wi_0_variant_0;
typedef struct __wi_allscale_wi_0_variant_0 __wi_allscale_wi_0_variant_0;

struct __wi_allscale_wi_0_variant_1;
typedef struct __wi_allscale_wi_0_variant_1 __wi_allscale_wi_0_variant_1;

struct __wi_allscale_wi_0_name {
    static const char* name() { return "__wi_allscale_wi_0"; }
};

using __wi_allscale_wi_0_work = allscale::work_item_description<int32_t, __wi_allscale_wi_0_name, allscale::no_serialization, __wi_allscale_wi_0_variant_0, __wi_allscale_wi_0_variant_1 >;

/* ------- Function Definitions --------- */
allscale::treeture<int32_t > allscale_fun_40(allscale::runtime::dependencies const& var_0, hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_1) {
    return allscale::spawn<__wi_allscale_wi_0_work >(hpx::util::get<0 >(var_1), hpx::util::get<1 >(var_1), hpx::util::get<2 >(var_1));
}
/* ------- Function Definitions --------- */
allscale::treeture<int32_t > IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_async_lambda_slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_returns_core_colon__colon_treeture_lt_std_colon__colon_result_of_t_lt__lparen_lambda_at__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_colon_8_colon_19_rparen___lparen_void_rparen__gt___gt_(IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 const& var_0) {
    return allscale::runtime::make_prec_operation<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, int32_t >(INS_INIT(hpx::util::tuple<IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 >){var_0, var_0}, &allscale_fun_40)((IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3 const&)IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3());
}
/* ------- Function Definitions --------- */
int32_t IMP_main() {
    allscale::treeture<int32_t > var_0 = IMP_allscale_colon__colon_api_colon__colon_user_colon__colon_async_lambda_slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_returns_core_colon__colon_treeture_lt_std_colon__colon_result_of_t_lt__lparen_lambda_at__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_colon_8_colon_19_rparen___lparen_void_rparen__gt___gt_(INS_INIT(IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19){});
    std::cout.operator<<(var_0.get_result()).operator<<(&std::endl);
    return 0;
}
/* ------- Function Definitions --------- */
allscale::treeture<int32_t > allscale_fun_2(hpx::util::tuple< > const& var_0) {
    return allscale::treeture<int32_t >(IMP_main());
}
struct __wi_main_variant_0 {
    static allscale::treeture<int32_t > execute(hpx::util::tuple< > const& var_0);
    static constexpr bool valid = true;
};

/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
int32_t IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19::operator()() const {
    return 12;
}
/* ------- Function Definitions --------- */
IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19::operator allscale_type_14() const {
    assert((bool)false && (bool)"This is an Insieme generated dummy function which should never be called");
}
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
/* ------- Function Definitions --------- */
int32_t allscale_fun_46(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0) {
    return (*(const IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19*)(&hpx::util::get<1 >(var_0))).operator()();
}
/* ------- Function Definitions --------- */
bool allscale_fun_44(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0) {
    return (bool)true;
}
struct allscale_type_56;
typedef struct allscale_type_56 allscale_type_56;

struct allscale_type_56 {
    char data[23];;
};

struct allscale_type_55;
typedef struct allscale_type_55 allscale_type_55;

struct allscale_type_55 {
    char data[161];;
};

/* ------- Function Definitions --------- */
allscale::treeture<int32_t > allscale_fun_49(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0) {
    struct insieme::utils::detail::LazyAssertion var_1 = (struct insieme::utils::detail::LazyAssertion const&)insieme::utils::detail::LazyAssertion((bool)false);
    if (var_1.operator bool()) {
        std::operator<<(std::operator<<(std::cerr, "\nAssertion failed in /home/zangerl/insieme_dev/allscale/code/include/allscale/compiler/../../../../api/code/api/include/allscale/api/user/operator/async.h:49 - "), "Should not be reached!");
    };
    return allscale::treeture<int32_t >((*(const IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19*)(&hpx::util::get<2 >(var_0))).operator()());
}
/* ------- Function Definitions --------- */
allscale::treeture<int32_t > allscale_fun_42(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0) {
    if (allscale_fun_44(var_0)) {
        return allscale::treeture<int32_t >(allscale_fun_46(var_0));
    } else {
        return allscale_fun_49(var_0);
    };
}
struct __wi_allscale_wi_0_variant_0 {
    static allscale::treeture<int32_t > execute(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0);
    static constexpr bool valid = true;
};

allscale::treeture<int32_t > __wi_allscale_wi_0_variant_0::execute(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0) {
    return allscale_fun_42(var_0);
}
/* ------- Function Definitions --------- */
int32_t allscale_fun_58(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0) {
    struct insieme::utils::detail::LazyAssertion var_1 = (struct insieme::utils::detail::LazyAssertion const&)insieme::utils::detail::LazyAssertion((bool)false);
    if (var_1.operator bool()) {
        std::operator<<(std::operator<<(std::cerr, "\nAssertion failed in /home/zangerl/insieme_dev/allscale/code/include/allscale/compiler/../../../../api/code/api/include/allscale/api/user/operator/async.h:49 - "), "Should not be reached!");
    };
    return (*(const IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19*)(&hpx::util::get<2 >(var_0))).operator()();
}
/* ------- Function Definitions --------- */
int32_t rec(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0) {
    if (allscale_fun_44(var_0)) {
        return allscale_fun_46(var_0);
    } else {
        return allscale_fun_58(var_0);
    };
}
/* ------- Function Definitions --------- */
allscale::treeture<int32_t > allscale_fun_57(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0) {
    return allscale::treeture<int32_t >(rec(var_0));
}
struct __wi_allscale_wi_0_variant_1 {
    static allscale::treeture<int32_t > execute(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0);
    static constexpr bool valid = true;
};

allscale::treeture<int32_t > __wi_allscale_wi_0_variant_1::execute(hpx::util::tuple<IMP_empty_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_api_slash_code_slash_api_slash_include_slash_allscale_slash_api_slash_user_slash__operator_div_async_dot_h_42_3, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19, IMP___anon_tagtype__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19_int_IMLOC__slash_home_slash_zangerl_slash_insieme_dev_slash_allscale_slash_test_slash_async_slash_basic_slash_basic_dot_cpp_8_19 > const& var_0) {
    return allscale_fun_57(var_0);
}
allscale::treeture<int32_t > __wi_main_variant_0::execute(hpx::util::tuple< > const& var_0) {
    return allscale_fun_2(var_0);
}
struct __wi_main_variant_1 {
    static allscale::treeture<int32_t > execute(hpx::util::tuple< > const& var_0);
    static constexpr bool valid = true;
};

allscale::treeture<int32_t > __wi_main_variant_1::execute(hpx::util::tuple< > const& var_0) {
    return allscale_fun_2(var_0);
}

